name: CI Tests
on:
  pull_request_target:
    types: [labeled]
    
jobs:
  trivial:
    runs-on: ubuntu-latest
    if: contains(github.event.pull_request.labels.*.name, 'ci:test')
    name: CI Machinery Tests
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Changed Files
        run: |
          echo "$GITHUB_EVENT_NAME"
          echo "Base Ref: $GITHUB_BASE_REF"
          URL="https://api.github.com/repos/${{ github.repository }}/pulls/${{ github.event.pull_request.number }}/files"
          FILES=$(curl -s -X GET -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" $URL | jq -r '.[] | .filename')
          echo "Files changed: $FILES"
      - name: show ci file
        run: echo "this file is checked in main"
      - name: show selected vars
        run: |
          echo "GITHUB_ACTOR: $GITHUB_ACTOR"
          echo "GITHUB_HEAD_REF:  $GITHUB_HEAD_REF"
          echo "GITHUB_BASE_REF:  $GITHUB_BASE_REF"
          echo "GITHUB_REF:  $GITHUB_REF"
          echo "GITHUB_REPOSITORY:  $GITHUB_REPOSITORY"
          echo "GITHUB_SHA:  $GITHUB_SHA"
          echo ${{ github.event.number }}
          echo ${{ github.event.pull_request.body }}
      - name: remove ci test tag
        uses: actions/github-script@a3e7071a34d7e1f219a8a4de9a5e0a34d1ee1293
        with:
          github-token: ${{secrets.GITHUB_TOKEN}}
          script: |
            github.issues.removeLabel({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              name: 'ci:run'
            })
            github.issues.removeLabel({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              name: 'ci:test'
            })
        continue-on-error: true
      - name: step conditional test should not run
        if: contains(github.event.pull_request.body, 'NO_TAG_HERE')
        run: echo "NO_TAG_HERE found (should not be)"
      - name: step conditional test should pass
        if: contains(github.event.pull_request.body, 'TAG_FOR_CHECK')
        run: echo "TAG_FOR_CHECK found, good job"
      - name: step conditional not check
        if: ${{ !contains(github.event.pull_request.body, 'NO_TAG_HERE') }}
        run: echo "NOT_TAG_HERE not found (negation conditional check passed!)"
#      - name: log in to the registry
#        run: echo ${{ secrets.CONTAINER_PAT }} | docker login ghcr.io -u jwithersci --password-stdin
#      - name: run private external container
#        run: docker run ghcr.io/jwithersci/priv-jwithersci:latest
#      - name: create json file
#        run: |
#          python3 .github/assets/write_json.py -f ./.tests/test.json
#      - name: commit ci info file
#        run: |
#          git config --local user.email "$(git log --format='%ae' HEAD^!)"
#          git config --local user.name "$(git log --format='%an' HEAD^!)"
#          git remote add github "https://$GITHUB_ACTOR:$GITHUB_TOKEN@github.com/$GITHUB_REPOSITORY.git"
#          git pull github ${GITHUB_REF}
#          git add .
#          git commit -m "adding ci data"
#          git push --force github HEAD:${GITHUB_HEAD_REF}
